name: 'Datadog Downtime Action'
description: 'This action allows you to create a downtime in Datadog.'
branding:
  icon: 'clock'
  color: 'purple'
author: 'Brooke Hatton'
inputs:
  downtime-minutes:
    required: false
    description: 'The number of minutes to set the downtime for'
    default: '5'
  message:
    required: false
    description: 'The message to include in the downtime'
    default: 'Scheduled downtime for deployment'
  scope:
    required: false
    description: 'The downtimes scope should be represented as a JSON.stringify array of strings, using key:value format for the scope(s) to which it applies. For instance, you may use ["*"] or ["env:prod,env:staging", "host:myhost.example.com"]'
    default: '["*"]'
  monitor-tags:
    required: false
    description: 'The monitor tags to include in the downtime. Should be a JSON.stringify array of strings ["env:prod,env:staging", "host:myhost.example.com"]'
  monitor-id:
    required: false
    description: 'A single monitor to which the downtime applies. If not provided, the downtime applies to all monitors.'
  site:
    required: false
    description: 'The site to create the downtime for e.g. datadoghq.eu'
    default: 'datadoghq.com'
  api-key:
    required: false
    description: 'The Datadog API key'
  app-key:
    required: false
    description: 'The Datadog APP key'
runs:
  using: 'node16'
  main: 'dist/index.js'
